export const siteConfig = {
  title: '像素小站',
  site: 'https://3229154448.github.io/pixel-astro-blog',
  author: 'Pixel',
  motto: '运气是计划之外的东西.',
  description: '一个像素风格的Astro博客主题',
  lang: 'zh-CN',
  theme: {
    primaryColor: '#e74c3c',
    secondaryColor: '#27ae60',
    accentColor: '#e74c3c',
    bgColor: '#e8e0d5',
    textColor: '#1a1a2e',
    cardBg: '#d4c8b8',
    borderColor: '#1a1a2e',
    codeBg: '#2d2d3f',
    codeColor: '#33ff33',
    borderRadius: '0px',
    sidebarWidth: 320,
  },
  typewriter: [
    '欢迎来到像素小站 🎮',
    '8-Bit Life, Infinite Possibilities ✨',
    '复古游戏，现代技术 🕹️',
    '像素世界，无限可能 🌟',
  ],
  navbar: [
    { name: '首页', link: '/' },
    { name: '朋友', link: '/links' },
    { name: '圈子', link: '/friends' },
    { name: '动态', link: '/talking' },
    { name: '昔日', link: '/archives' },
    { name: '留言', link: '/message' },
    { name: '关于', link: '/about' },
  ],
  sidebar: {
    showCategories: true,
    showTags: true,
    showRecentPosts: true,
    showAnnouncement: true,
    announcement: '🎮 欢迎来到像素小站！这是一个基于Astro的像素风博客主题。按 ↑↑↓↓←→←→BA 有惊喜！',
  },
  comment: {
    enable: false,
    type: 'twikoo' as 'twikoo' | 'waline',
    twikoo: { envId: '' },
    waline: { serverURL: '' },
  },
  reward: {
    enable: true,
    alipay: '/assets/images/alipay.webp',
    wechat: '/assets/images/wechat.webp',
    comment: '感谢支持像素小站！',
  },
  rss: { enable: true, title: '像素小站', description: '一个像素风格的Astro博客主题' },
  sitemap: { enable: true },
};

export type SiteConfig = typeof siteConfig;
