export const siteConfig = {
  title: '像素小站',
  site: 'https://pixel-astro-blog.github.io',
  author: 'Pixel',
  motto: '8-Bit Life, Infinite Possibilities.',
  description: '一个像素风格的Astro博客主题',
  lang: 'zh-CN',
  theme: {
    primaryColor: '#41a6f6',
    secondaryColor: '#f77622',
    accentColor: '#e43b44',
    bgColor: '#1a1c2c',
    textColor: '#f4f4f4',
    cardBg: '#262b44',
    borderColor: '#333c57',
    codeBg: '#0d0f1a',
    codeColor: '#33ff33',
    borderRadius: '0px',
    sidebarWidth: 320,
  },
  typewriter: [
    '欢迎来到像素小站 🎮',
    '8-Bit Life, Infinite Possibilities ✨',
    '复古游戏，现代技术 🕹️',
    '像素世界，无限可能 🌟',
  ],
  navbar: [
    { name: '首页', link: '/' },
    { name: '归档', link: '/archives' },
    { name: '分类', link: '/categories' },
    { name: '标签', link: '/tag' },
    { name: '动态', link: '/talking' },
    { name: '圈子', link: '/friends' },
    { name: '友链', link: '/links' },
    { name: '留言', link: '/message' },
    { name: '关于', link: '/about' },
  ],
  sidebar: {
    showCategories: true,
    showTags: true,
    showRecentPosts: true,
    showAnnouncement: true,
    announcement: '🎮 欢迎来到像素小站！这是一个基于Astro的像素风博客主题。',
  },
  comment: {
    enable: false,
    type: 'twikoo' as 'twikoo' | 'waline',
    twikoo: { envId: '' },
    waline: { serverURL: '' },
  },
  reward: {
    enable: true,
    alipay: '/assets/images/alipay.webp',
    wechat: '/assets/images/wechat.webp',
    comment: '感谢支持像素小站！',
  },
  rss: { enable: true, title: '像素小站', description: '一个像素风格的Astro博客主题' },
  sitemap: { enable: true },
};

export type SiteConfig = typeof siteConfig;
